[sample_clock]
clock_source = "Internal"
rate = "100 MS/s"
edge = "Rising"

[channels]
enabled = [true, true, false, false]
coupling = ["DC", "DC", "DC", "DC"]
impedance = ["50 ohm", "50 ohm", "50 ohm", "50 ohm"]
range = ["2 V", "2 V", "2 V", "2 V"]

[trigger]
source = "External"
slope = "Positive"
level = 0